Update yml

diff --git a/.github/workflows/dev-deployment.yml b/.github/workflows/dev-deployment.yml
--- a/.github/workflows/dev-deployment.yml
+++ b/.github/workflows/dev-deployment.yml
@@ -100,7 +100,6 @@ jobs:
 
     # Validate deployment (Check Only)
     - name: Validate Deployment
-      id: validate_step # Assign an ID to this step to access its outputs
       if: env.SKIP_DEPLOYMENT == 'false'
       run: |
         echo "Starting validation deployment..."
@@ -118,12 +117,18 @@ jobs:
         echo "validation_id=$DEPLOY_ID" >> $GITHUB_OUTPUT
         echo "Validation ID: $DEPLOY_ID"
 
-    # Quick Deploy using Validation ID
-    - name: Quick Deployment
-      if: success() && steps.validate_step.outputs.validation_id
+    - name: Attempt Quick Deploy, else run a full deployment
       run: |
-        echo "Starting quick deployment using ID: ${{ steps.validate_step.outputs.validation_id }}"
-        sf project deploy quick --job-id ${{ steps.validate_step.outputs.validation_id }} \
+        set +e
+        sf project deploy quick \
+          --job-id ${{ env.validation_id }} \
           --target-org target-org \
           --wait 30 \
           --verbose
+        if [ $? -ne 0 ]; then
+          echo "Quick deploy failed, falling back to full deploy..."
+          sf project deploy start \
+            --target-org target-org \
+            --wait 30 \
+            --verbose
+        fi
